development:
  secret_token: "pk_test_51JwSpDB3epToDoU1R2YTXGAFSTIQytcpl30xHDsh3l39Vk87mhtHBD9bgrMBNSNwVE6EVUAbqXZlPYouv1p1R5OG00ZnYBCrbJ"
  secret_key_base: "sk_test_51JwSpDB3epToDoU17c5RBAkdz3GfdqFBsPQC7D12iMzLbikarCnoZwAwKa3LNOo7ZuFlnghPtyG0up0aEZ3mvl6R00fBinnLhy"
